### ISSUE TITLE
[BUG] Passive Mobs are aggressive by default

### ISSUE THREAD

**Issue by Elska85** [Dev-Gio-Modding/Passive_Enchantments#1]
**Describe the bug**
Passive mobs are by default aggressive and really strong. Most entities get 2-3 shot by a cow or sheep.

**Expected behavior**
Expected mobs to be passive without curse. 

**Versions (please complete the following information):**
 - Minecraft: [e.g. 1.21.1]
 - Fabric Loader [e.g. 0.16.4]
 - Fabric API [e.g. 0.103.0+1.21.1]

**Comment by JRTerry-Modding** [comment]
I will look at this in over the next day or 2.

**Comment by JRTerry-Modding** [comment]
Fixed
